spring:
  application:
    name: language-trainer

  datasource:
    driver-class-name: org.postgresql.Driver

#    url: jdbc:postgresql://localhost:5432/language_trainer
#    username: postgres
#    password: 123
    url: jdbc:postgresql://pg3.sweb.ru:5432/zheshelist
    username: zheshelist
    password: postQazwsx258794613

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  mvc:
    hidden method:
      filter:
        enabled: true
