spring:
  application:
    name: language-trainer

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg3.sweb.ru:5432/zheshelist
    username: zheshelist
    password: postQazwsx258794613

  jpa:
#    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update  # Или 'create', чтобы создать таблицы с нуля

  sql:
    init:
      mode: always

  mvc:
    hidden method:
      filter:
        enabled: true
